name: Clean Architecture CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release
        continue-on-error: true

      - name: Publish API
        run: dotnet publish Api/Api.csproj -c Release -o publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: publish
